using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class CombineFruits : MonoBehaviour
//ï¿½tï¿½ï¿½ï¿½[ï¿½cï¿½ÉƒAï¿½^ï¿½bï¿½`ï¿½ï¿½ï¿½ÄCï¿½tï¿½ï¿½ï¿½[ï¿½cï¿½Ì“ï¿½ï¿½ï¿½ï¿½è”»ï¿½ï¿½Æï¿½ñ‘€ï¿½Égï¿½ï¿½
{
    [Header("Fruit")]
    [SerializeField] private GameObject combinedFruit;//ï¿½Å‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìƒtï¿½ï¿½ï¿½[ï¿½cï¿½Ìƒvï¿½ï¿½ï¿½nï¿½uï¿½ï¿½ï¿½Lï¿½^
    private GameObject generatedFruit;//ï¿½ï¿½ï¿½Û‚Éï¿½ï¿½İoï¿½ï¿½ï¿½ê‚½ï¿½tï¿½ï¿½ï¿½[ï¿½cï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½iï¿½[
    public bool isAlreadyDropped = false;//ï¿½rï¿½ï¿½ï¿½Éƒhï¿½ï¿½ï¿½bï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½ ï¿½rï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ñoï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ğ”»’è‚·ï¿½é‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½Å‚ï¿½false
    public int fruitID;//ãƒ‰ãƒ­ãƒƒãƒ—ãƒ•ãƒ«ãƒ¼ãƒ„ã®ID
    [Header("SE")]
    public GameObject audioObject;//ï¿½|ï¿½ï¿½ï¿½ÌŒï¿½ï¿½Ê‰ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    AudioSource audioSource;//ï¿½|ï¿½ï¿½ï¿½ÌŒï¿½ï¿½Ê‰ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    [SerializeField] private AudioClip pon;//ï¿½|ï¿½ï¿½ï¿½ÌŒï¿½ï¿½Ê‰ï¿½
    [Header("Score")]
    public Score score;//ï¿½Xï¿½Rï¿½Aï¿½Ì‚ï¿½ï¿½
    [Header("Halloween")]
    [SerializeField] private bool isPumpkin = false;//ãƒãƒ­ã‚¦ã‚£ãƒ³ä»•æ§˜ï¼šã‹ã¼ã¡ã‚ƒã‹ã©ã†ã‹

    private void Start()
    {
        if (this.gameObject.name == "None(Clone)") Destroy(this.gameObject);//ï¿½Xï¿½Cï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ç©ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        audioObject = GameObject.FindGameObjectWithTag("Audio");
        audioSource = audioObject.GetComponent<AudioSource>();
        if (SceneManager.GetActiveScene().name != "TitleScene")
            score = GameObject.FindGameObjectWithTag("Score").GetComponent<Score>();
    }
    //ï¿½Õ“Ë‚ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½Éƒtï¿½ï¿½ï¿½[ï¿½cï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½
    void OnCollisionEnter(Collision collision)
    {
        if (gameObject.CompareTag("Fruit"))//ã“ã‚ŒãŒãƒ•ãƒ«ãƒ¼ãƒ„ãªã‚‰(è‡ªåˆ†ãŒã‚­ãƒ£ãƒ³ãƒ‡ã‚£ã®å ´åˆã¯ä½•ã‚‚èµ·ã“ã•ãªã„ã€€ã¶ã¤ã‹ã£ãŸãƒ•ãƒ«ãƒ¼ãƒ„ã®é–¢æ•°ã‚’ãƒˆãƒªã‚¬ãƒ¼ã•ã›ã‚‹)
        {
            if (collision.gameObject.CompareTag("Fruit"))                         // FruitåŒå£«ã§ã¶ã¤ã‹ã£ãŸã‚‰
            {
                if (collision.gameObject.name == this.gameObject.name)
                {//åŒä¸€åã®ãƒ•ãƒ«ãƒ¼ãƒ„ãªã‚‰
                    if (collision.gameObject.GetComponent<CombineFruits>().fruitID < fruitID)
                    {//2ã¤ã®ã†ã¡ãƒ•ãƒ«ãƒ¼ãƒ„IDãŒå°ã•ã„æ–¹ã«ã¤ã„ã¦(å…ˆã«è½ã¨ã•ã‚ŒãŸã‚‚ã®ã«ã¤ã„ã¦)
                        generatedFruit = Instantiate(combinedFruit, this.transform.position, this.transform.rotation);//å…ˆã«è½ã¨ã•ã‚ŒãŸãƒ•ãƒ«ãƒ¼ãƒ„ã®ä½ç½®ã«é€²åŒ–å…ˆãƒ•ãƒ«ãƒ¼ãƒ„ã‚’å…¥ã‚Œã‚‹
                        generatedFruit.GetComponent<Rigidbody>().useGravity = true;//é‡åŠ›è½ä¸‹ã•ã›ã¾ã™;
                        generatedFruit.GetComponent<CombineFruits>().isAlreadyDropped = true;//æ—¢ã«è½ã¨ã•ã‚ŒãŸç‰©ä½“ã§ã‚ã‚‹æƒ…å ±
                        generatedFruit.GetComponent<CombineFruits>().fruitID = fruitID;//é †ç•ªã®å¼•ç¶™ã
                        audioSource.PlayOneShot(pon);//SEã‚’ãªã‚‰ã™
                        score.UpdateScore(this.name);//ãƒ•ãƒ«ãƒ¼ãƒ„ã®ç¨®é¡ã«å¿œã˜ã¦ã‚¹ã‚³ã‚¢ã‚’å‡ºã™
                    }
                    Destroy(collision.gameObject);
                    Destroy(this.gameObject);
                }
            }
            else if (collision.gameObject.CompareTag("Candy"))//ãƒãƒ­ã‚¦ã‚£ãƒ³ä»•æ§˜ã®ã‚­ãƒ£ãƒ³ãƒ‡ã‚£ã®å®Ÿè£…ã‚­ãƒ£ãƒ³ãƒ‡ã‚£ã¨ã¶ã¤ã‹ã£ãŸãªã‚‰
            {
                if (!isPumpkin)//ã‚«ãƒœãƒãƒ£ã¨ã‚­ãƒ£ãƒ³ãƒ‡ã‚£ãŒã¶ã¤ã‹ã£ãŸã‚‰ä¸¡è€…æ¶ˆæ»…ã™ã‚‹ã®ã§ã“ã“ã¯çœç•¥
                {
                    generatedFruit = Instantiate(combinedFruit, this.transform.position, this.transform.rotation);//è‡ªåˆ†ã®ä½ç½®ã«é€²åŒ–å…ˆãƒ•ãƒ«ãƒ¼ãƒ„ã‚’å‡ºã™
                    generatedFruit.GetComponent<Rigidbody>().useGravity = true;//é‡åŠ›è½ä¸‹ã•ã›ã¾ã™;
                    generatedFruit.GetComponent<CombineFruits>().isAlreadyDropped = true;//æ—¢ã«è½ã¨ã•ã‚ŒãŸç‰©ä½“ã§ã‚ã‚‹æƒ…å ±
                    generatedFruit.GetComponent<CombineFruits>().fruitID = fruitID;//é †ç•ªã®å¼•ç¶™ã
                }
                audioSource.PlayOneShot(pon);//SEã‚’ãªã‚‰ã™
                if (this.gameObject.name != "Watermelon(Clone)") score.UpdateScore(this.name);//ãƒ•ãƒ«ãƒ¼ãƒ„ã®ç¨®é¡ã«å¿œã˜ã¦ã‚¹ã‚³ã‚¢ã‚’å‡ºã™ ãŸã ã—ã‚¹ã‚¤ã‚«ã‚’ã‚­ãƒ£ãƒ³ãƒ‡ã‚£ã«ã‚ã¦ãŸã¨ãã«ã¯ãªã«ã‚‚èµ·ã“ã‚‰ãªã„
                Destroy(collision.gameObject);
                Destroy(this.gameObject);
            }
        }
    }
}
