using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.Events;
using TMPro;
using System.Runtime.CompilerServices;

public class FruitAppear : MonoBehaviour
{
    [SerializeField] private GameObject[] fruit;//ãƒ•ãƒ«ãƒ¼ãƒ„
    [SerializeField] private GameObject respawnFruit;//ãƒªã‚¹ãƒãƒ¼ãƒ³åœ°ç‚¹
    [SerializeField] private GameObject uiFruit;//Nextã®UIã¨ã—ã¦è¡¨ç¤ºã™ã‚‹ãƒ•ãƒ«ãƒ¼ãƒ„
    [SerializeField] private GameObject nextFruits;//æ¬¡ã«è½ã¨ã™ãƒ•ãƒ«ãƒ¼ãƒ„
    [SerializeField] private GameObject currentFruits;//ä»Šè½ã¨ã™ãƒ•ãƒ«ãƒ¼ãƒ„
    public bool isGameOver = false;//ã‚²ãƒ¼ãƒ ã‚ªãƒ¼ãƒãƒ¼åˆ¤å®š

    public GameObject audioObject;//éŸ³é–¢ä¿‚
    AudioSource audioSource;//éŸ³é–¢ä¿‚
    [SerializeField] private AudioClip drop, reset, countDown, finish;//SE
    public int totalFruitsNumber = 0;//ä»Šã®ãƒ•ãƒ«ãƒ¼ãƒ„ãƒŠãƒ³ãƒãƒ¼
    public Score score;
    public CSVReader csvReader;
    public TextMeshProUGUI gameoverText;
    bool isGameNow = false;
    [SerializeField] private TextMeshProUGUI countDownText;
    private int limitTime;
    [SerializeField] public int remainTime;

    void Start()
    {
        limitTime = remainTime;//åˆ¶é™æ™‚é–“ã‚’è¨˜éŒ²
        remainTime += 4;//ã‚«ã‚¦ãƒ³ãƒˆãƒ€ã‚¦ãƒ³åˆ†ã®ï¼”secè¿½åŠ 
    }
    void fruitAppear()
    {

        int n = Random.Range(0, fruit.Length);//nå€‹ã®ãƒ•ãƒ«ãƒ¼ãƒ„ã®ä¸­ã‹ã‚‰ãƒ©ãƒ³ãƒ€ãƒ ã«
        currentFruits = Instantiate(fruit[n], respawnFruit.transform.position, respawnFruit.transform.rotation);//ï¿½ï¿½ÌˆÊ’uï¿½Éï¿½ï¿½Ìƒtï¿½ï¿½ï¿½[ï¿½cï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        currentFruits.GetComponent<CombineFruits>().isAlreadyDropped = false;//ï¿½rï¿½ï¿½ï¿½Éƒhï¿½ï¿½ï¿½bï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½ ï¿½rï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ñoï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ğ”»’è‚·ï¿½é‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½Å‚ï¿½false
        currentFruits.GetComponent<CombineFruits>().fruitID = totalFruitsNumber;
        totalFruitsNumber++;

        n = Random.Range(0, fruit.Length);//ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½Åƒtï¿½ï¿½ï¿½[ï¿½cï¿½ï¿½ï¿½ï¿½
        nextFruits = Instantiate(fruit[n], uiFruit.transform.position, uiFruit.transform.rotation);//uiï¿½ÌˆÊ’uï¿½Éï¿½ï¿½Ìƒtï¿½ï¿½ï¿½[ï¿½cï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        nextFruits.transform.parent = uiFruit.transform;//ï¿½êï¿½ÉUï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½
        nextFruits.GetComponent<CombineFruits>().isAlreadyDropped = false;//ï¿½hï¿½ï¿½ï¿½bï¿½vï¿½ï¿½ï¿½Ä‚È‚ï¿½ï¿½İ‚ï¿½ï¿½
        nextFruits.GetComponent<CombineFruits>().fruitID = totalFruitsNumber;
        totalFruitsNumber++;
    }

    // Update is called once per frame
    public void FruitDropped()
    {
        if (!isGameOver)
        {
            //currentFruits.transform.parent = null;//ï¿½eï¿½ï¿½ï¿½ï¿½ï¿½@VRï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ç‚¢ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½
            audioSource = audioObject.GetComponent<AudioSource>();
            audioSource.PlayOneShot(drop);//ï¿½Ğ‚ï¿½[ï¿½ï¿½

            StartCoroutine(DelayCoroutine(1.0f, () =>
            {
                RespawnFruit();
            }));
        }
        /*else
        {
            if (Input.GetKeyDown(KeyCode.R)) SceneManager.LoadScene(SceneManager.GetActiveScene().name);//ï¿½ï¿½ï¿½È‚ï¿½ï¿½ï¿½
        }*/

    }

    void Update()
    {
        if (!isGameNow)
        {
            if (Input.GetKeyDown(KeyCode.Space))
            {
                audioSource = audioObject.GetComponent<AudioSource>();
                audioSource.PlayOneShot(countDown);//321ã½ãƒ¼ã‚“ã®ã‚„ã¤ã‚’æµã™
                remainTimeUpdate();
                Invoke("fruitAppear", 3.0f); // é–¢æ•°fruitAppearã‚’3ç§’å¾Œã«å®Ÿè¡Œ
            }
        }
    }

    void remainTimeUpdate()
    {
        remainTime--;
        if (remainTime > 0)//æ®‹ã‚Šæ™‚é–“ã‚’æ›´æ–°ã—ã¾ã™
        {
            if (remainTime > limitTime) countDownText.text = limitTime.ToString();//ã‚«ã‚¦ãƒ³ãƒˆãƒ€ã‚¦ãƒ³æ™‚ã¯å‹•ã‹ã•ãªã„
            else countDownText.text = remainTime.ToString();
            Invoke("remainTimeUpdate", 1.0f); // é–¢æ•°remainTimeUpdateã‚’1ç§’å¾Œã«å®Ÿè¡Œ
        }
        else if (remainTime >= 0)//æ™‚é–“ãŒãŠã‚ã£ãŸã‚‰
        {
            if (!isGameOver)
            {
                GameObject[] droppedFruits = GameObject.FindGameObjectsWithTag("Fruit");
                foreach (GameObject droppedFruit in droppedFruits)
                {
                    droppedFruit.GetComponent<Rigidbody>().isKinematic = true;//å…¨ã¦ã®ãƒ•ãƒ«ãƒ¼ãƒ„ã‚’åœæ­¢ã•ã›ã¾ã™
                }
                isGameOver = true;
                countDownText.text = "Finish";
                audioSource = audioObject.GetComponent<AudioSource>();
                audioSource.PlayOneShot(finish);//ãŠã‚ã‚Šã®ã‚„ã¤ã‚’æµã™
            }
        }
    }


    private void RespawnFruit()
    {
        if (currentFruits) currentFruits.GetComponent<CombineFruits>().isAlreadyDropped = true;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚È‚ï¿½ï¿½ï¿½ÎŠï¿½ï¿½Éƒhï¿½ï¿½ï¿½bï¿½vï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½Ì‚É‚ï¿½ï¿½ï¿½
        //nextFruits.transform.parent = null;//ï¿½eï¿½ï¿½ï¿½ï¿½
        nextFruits.transform.position = respawnFruit.transform.position;//ï¿½ï¿½ÌˆÊ’uï¿½Éï¿½ï¿½Ìƒtï¿½ï¿½ï¿½[ï¿½cï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        currentFruits = nextFruits;//ï¿½ï¿½ÉˆÚ“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½[ï¿½cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½tï¿½ï¿½ï¿½[ï¿½cï¿½É‚ï¿½ï¿½ï¿½
        //currentFruits.transform.parent = respawnFruit.transform;//ï¿½êï¿½ÉˆÚ“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½@VRï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ç‚¢ï¿½ï¿½È‚ï¿½ï¿½Xï¿½Nï¿½ï¿½ï¿½vï¿½g

        int n = Random.Range(0, fruit.Length);//ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½Åƒtï¿½ï¿½ï¿½[ï¿½cï¿½ï¿½ï¿½ï¿½

        nextFruits = Instantiate(fruit[n], uiFruit.transform.position, uiFruit.transform.rotation);//uiï¿½ÌˆÊ’uï¿½Éï¿½ï¿½Ìƒtï¿½ï¿½ï¿½[ï¿½cï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        //nextFruits.transform.parent = uiFruit.transform;//ï¿½êï¿½ÉUï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½
        nextFruits.GetComponent<CombineFruits>().isAlreadyDropped = false;//ï¿½hï¿½ï¿½ï¿½bï¿½vï¿½ï¿½ï¿½Ä‚È‚ï¿½ï¿½İ‚ï¿½ï¿½
        nextFruits.GetComponent<CombineFruits>().fruitID = totalFruitsNumber;//nç•ªç›®ã®ãƒ•ãƒ«ãƒ¼ãƒ„ã ã‚ˆï¼
        totalFruitsNumber++;
    }

    private IEnumerator DelayCoroutine(float seconds, UnityAction callback)//ï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½ï¿½ï¿½nï¿½bï¿½ãˆï¿½ï¿½ï¿½ï¿½ï¿½Å‚ï¿½ï¿½ï¿½
    {
        yield return new WaitForSeconds(seconds);
        callback?.Invoke();
    }

    public void Restart()
    {
        audioSource = audioObject.GetComponent<AudioSource>();
        audioSource.PlayOneShot(reset);//ï¿½Ğ‚ï¿½[ï¿½ï¿½

        /*1.ã‚²ãƒ¼ãƒ ã‚ªãƒ¼ãƒãƒ¼ã®è§£é™¤*/
        isGameOver = false;
        gameoverText.text = "";
        totalFruitsNumber = 0;

        /*2.å…¨ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®å‰Šé™¤*/
        GameObject[] droppedFruits = GameObject.FindGameObjectsWithTag("Fruit");//ï¿½ï¿½ï¿½Éƒhï¿½ï¿½ï¿½bï¿½vï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½[ï¿½cï¿½^ï¿½Oï¿½ï¿½Sï¿½ÄŠiï¿½[
        foreach (GameObject droppedFruit in droppedFruits)
        {
            Destroy(droppedFruit);
        }

        GameObject[] droppedCandies = GameObject.FindGameObjectsWithTag("Candy");//ï¿½ï¿½ï¿½Éƒhï¿½ï¿½ï¿½bï¿½vï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½[ï¿½cï¿½^ï¿½Oï¿½ï¿½Sï¿½ÄŠiï¿½[
        foreach (GameObject droppedCandy in droppedCandies)
        {
            Destroy(droppedCandy);
        }

        /*3.ã‚¹ã‚³ã‚¢ãƒªã‚»ãƒƒãƒˆ*/
        score.score = 0;
        csvReader.RankingUpdate();
        score.scoreToString();

        /*4.åˆæœŸçŠ¶æ…‹ã®æ§‹ç¯‰*/
        int n = Random.Range(0, fruit.Length);//nå€‹ã®ãƒ•ãƒ«ãƒ¼ãƒ„ã®ä¸­ã‹ã‚‰ãƒ©ãƒ³ãƒ€ãƒ ã«
        currentFruits = Instantiate(fruit[n], respawnFruit.transform.position, respawnFruit.transform.rotation);//ï¿½ï¿½ÌˆÊ’uï¿½Éï¿½ï¿½Ìƒtï¿½ï¿½ï¿½[ï¿½cï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        currentFruits.GetComponent<CombineFruits>().isAlreadyDropped = false;//ï¿½rï¿½ï¿½ï¿½Éƒhï¿½ï¿½ï¿½bï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½ ï¿½rï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ñoï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ğ”»’è‚·ï¿½é‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½Å‚ï¿½false
        currentFruits.GetComponent<CombineFruits>().fruitID = totalFruitsNumber;
        totalFruitsNumber++;

        n = Random.Range(0, fruit.Length);//ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½Åƒtï¿½ï¿½ï¿½[ï¿½cï¿½ï¿½ï¿½ï¿½
        nextFruits = Instantiate(fruit[n], uiFruit.transform.position, uiFruit.transform.rotation);//uiï¿½ÌˆÊ’uï¿½Éï¿½ï¿½Ìƒtï¿½ï¿½ï¿½[ï¿½cï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        nextFruits.transform.parent = uiFruit.transform;//ï¿½êï¿½ÉUï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½
        nextFruits.GetComponent<CombineFruits>().isAlreadyDropped = false;//ï¿½hï¿½ï¿½ï¿½bï¿½vï¿½ï¿½ï¿½Ä‚È‚ï¿½ï¿½İ‚ï¿½ï¿½
        nextFruits.GetComponent<CombineFruits>().fruitID = totalFruitsNumber;
        totalFruitsNumber++;

    }
}
